### ISSUE TITLE
Command line string limitations

### ISSUE THREAD

**Issue by mapero** [jni4net/jni4net#31]
Hi,

I use jni4net to wrap a large c# assembly. The jar command in the build.cmd generated by proxygen was about > 10000 characters. The maximum number of allowed characters is  8191 (see [Microsoft](https://support.microsoft.com/en-us/kb/830473) ).

Proxygen should split long commands into multiple lines to support large assemblies:

```
jar cvf test.j4n.jar -C .....
jar uvf test.j4n.jar -C .....
```

Thanks.

**Comment by pavelsavara** [comment]
the batch file generator is rather hack I have no desire to improve it. 
Proper solution would be to generate .csproj file for MSBuild.

**Comment by DimaDubyk** [comment]
Workaround.
Cheap solution is to update build.cmd manually after generation and extract arguments to be taken from files. examples can be taken from java docs:
http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html (COMMAND LINE ARGUMENT FILES)

Also jar can be created using root folder instead of files array because all directories are processed recursively for inputfiles argument.
see: http://docs.oracle.com/javase/7/docs/technotes/tools/windows/jar.html

**Comment by sansjunk** [comment]
@DimaDubyk , I ran into the same issue. Thanks for the suggested work around.
